apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: bonus
    namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://172.18.0.2/root/awesome_louisa.git'
    path: .
    targetRevision: HEAD
    directory:
      jsonnet:
        tlas:
          - name: ''
            value: ''
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
